name: InboxCritters
options:
  bundleIdPrefix: com.foculoom
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "20260226.1"
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  InboxCritters:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/InboxCritters
    dependencies:
      - sdk: SpriteKit.framework
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.inboxcritters
        PRODUCT_NAME: "Inbox Critters"
        PRODUCT_MODULE_NAME: InboxCritters
        INFOPLIST_FILE: Sources/InboxCritters/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: "RZWT5WST77"
        CODE_SIGN_STYLE: Automatic

  InboxCrittersTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests/InboxCrittersTests
    dependencies:
      - target: InboxCritters
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.inboxcritters.tests
        DEVELOPMENT_TEAM: "RZWT5WST77"
        CODE_SIGN_STYLE: Automatic
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Inbox Critters.app/Inbox Critters"
        BUNDLE_LOADER: "$(TEST_HOST)"

schemes:
  InboxCritters:
    build:
      targets:
        InboxCritters: all
        InboxCrittersTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: InboxCrittersTests
          randomExecutionOrder: true
      coverageTargets:
        - InboxCritters
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
